.workflows: main.yml: Improve hardware flashing
Signed-off-by: Benjamin Braddock <benjamin.braddock@thecapablehub.org>

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -83,11 +83,19 @@ jobs:
            run: |
               sudo apt update && sudo apt install -y bmap-tools
 
+              if [ ! -e /dev/disk/by-id/usb-ARM_M1SDP_*0 ]; then echo "Morello firmware drive not found!"; exit 1; fi
+
               sudo usbrelay HURTM_1=0
-              sudo dd if=board-firmware-sd-image.img of=/dev/disk/by-id/usb-ARM_M1SDP_500541683007-0:0
-              sudo bmaptool copy --nobmap usb-image-morello-soc.wic /dev/disk/by-id/usb-SanDisk_Cruzer_Blade_00016104110624091916-0:0
+              for i in {0..10}; do echo "Waiting for USB drive...."; if [ -e /dev/disk/by-id/usb-SanDisk_*0 ]; then break; fi; sleep 0.5; done
+              if [ ! -e /dev/disk/by-id/usb-SanDisk_*0 ]; then echo "USB drive not found!"; exit 1; fi
+
+              echo "Flashing firmware image.."
+              sudo dd if=board-firmware-sd-image.img of=$(ls /dev/disk/by-id/usb-ARM_M1SDP_*0) bs=512
+              echo "Flashing WIC image.."
+              sudo bmaptool copy --nobmap usb-image-morello-soc.wic /dev/disk/by-id/usb-SanDisk_*0
               sync
               sudo usbrelay HURTM_1=1
+
 
          - name: Boot and test firmware
            shell: bash
